import { defineArrayMember, defineField, defineType } from 'sanity'

/**
 * One advocate's reading of a clause. Generated by Gemini — it argues, it
 * never rules. `textualEvidence` must be verbatim quotes from the clause
 * text; that constraint is what keeps the debate anchored to the document
 * instead of drifting into generic legal-sounding prose.
 */
export const interpretationType = defineType({
  name: 'interpretation',
  title: 'Interpretation',
  type: 'document',
  groups: [
    { name: 'argument', title: 'Argument', default: true },
    { name: 'evidence', title: 'Evidence' },
    { name: 'graph', title: 'Reference Graph' },
  ],
  fields: [
    defineField({
      name: 'clause',
      title: 'Clause',
      type: 'reference',
      group: 'argument',
      to: [{ type: 'clause' }],
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'side',
      title: 'Side',
      type: 'string',
      group: 'argument',
      options: {
        list: [
          { title: 'A — Customer-Friendly', value: 'A' },
          { title: 'B — Operations-Focused', value: 'B' },
        ],
        layout: 'radio',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Interpretation Title',
      type: 'string',
      group: 'argument',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'summary',
      title: 'Summary',
      type: 'text',
      rows: 2,
      group: 'argument',
    }),
    defineField({
      name: 'argument',
      title: 'Argument',
      type: 'text',
      rows: 10,
      group: 'argument',
      description: 'The advocate’s reasoning. This must argue, not decide.',
    }),
    defineField({
      name: 'textualEvidence',
      title: 'Textual Evidence',
      type: 'array',
      group: 'evidence',
      of: [defineArrayMember({ type: 'string' })],
      description:
        'Verbatim quotes from the clause. An interpretation with no evidence is rejected and regenerated.',
    }),
    defineField({
      name: 'citedPrecedent',
      title: 'Precedent Relied Upon',
      type: 'array',
      group: 'graph',
      of: [defineArrayMember({ type: 'reference', to: [{ type: 'precedent' }] })],
      description:
        'Prior rulings this advocate actually invoked. Only populated from precedent that was genuinely supplied in the prompt — the model cannot invent these.',
    }),
  ],
  preview: {
    select: {
      side: 'side',
      title: 'title',
      clause: 'clause.title',
    },
    prepare({ side, title, clause }) {
      return {
        title: `${side === 'B' ? 'Advocate B' : 'Advocate A'} — ${title ?? 'Untitled'}`,
        subtitle: clause ?? 'Orphaned interpretation',
      }
    },
  },
})
